import "./globals.css";
import Navbar from "@/components/navbar";
import Footer from "@/components/footer";
import type { Metadata } from "next";
import { Raleway } from "next/font/google";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import Script from "next/script";

const raleway = Raleway({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Rehm Hof",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <Script
          async
          defer
          src="https://cdn.feedbucket.app/assets/feedbucket.js"
          data-feedbucket="jYcMFi5CS92ZSac6C82H"
        ></Script>
      </head>
      <body className={`${raleway.className} bg-white`}>
        <Navbar />
        {children}
        <Footer />
        <ToastContainer />
      </body>
    </html>
  );
}
