export const SENDGRID_API_KEY = process.env.NEXT_PUBLIC_SENDGRID_API_KEY;
export const SENDGRID_EMAIL_FROM = process.env.NEXT_PUBLIC_SENDGRID_EMAIL_FROM;
export const SENDGRID_EMAIL_TO = process.env.NEXT_PUBLIC_SENDGRID_EMAIL_TO;
